### ISSUE TITLE
Return Router to SendUpdate Format

### ISSUE THREAD

**Issue by miratepuffin** [Raphtory/Raphtory#103]
Router API was changed to run in a more optimised manner, however, this has caused some user issues and needs to be wrapped in a better API. (Removing the need to create your own update data structure).

**Comment by miratepuffin** [comment]
On second thoughts on this one, given the new changes to the Spout and its transformation into a Datasource, I think it may make some sense to do the same thing here, call it a graph builder or something. @imanehaf  Whats you thoughts on this?

**Comment by imanehaf** [comment]
From a user perspective, the router doesn't seem to be as heavy on the message handling as the spout was. But I agree it might be a good idea to clean up the router in the same way to polish things around. I am curious about the effect on performance this 'doing things in the background' is gonna entail though (as in is it going to solve some issues at the expense of taking longer to ingest?)
