### ISSUE TITLE
resolving vertices references based on hashed identifiers

### ISSUE THREAD

**Issue by niallroche** [Raphtory/Raphtory#108]
I am trying to resolve an issue where each vertex added has a unique numeric identifier, but it is too big to fit in a long. I can hash this id, but this makes it difficult to resolve to the source data when looking up query outputs such as PageRank etc. In reality, I think this will also apply to any situation where non-numeric identifiers need to be hashed to fit into a long.

I was wondering if there was any recommendations on how to handle this?

Some things that occured to me included:
1) Add a parameter to lookup and resolve in the Analytics API - maybe a variation on the serialisation logic filtered by an id range as an input param to the API param (if not easy/possible potentially loaded from a file )
2) As a short term workaround maintain an index in each Router between the hashed version and the full id and a way to look up and or/potentially serialise the index(s) after ingestion and processing is complete
3) Provide a query interface directly to the underlying data that will enable a direct id lookup and retrieve

**Comment by narnolddd** [comment]
Possibly (partially) resolved by #225 which allows a string "name" property for vertices in the graph builder and by default algorithms return the vertex name, or the hashed identifier if it does not exist.
