### ISSUE TITLE
Improve usability of pulling latest jar from Raphtory issues

### ISSUE THREAD

**Issue by Haaroon** [Raphtory/Raphtory#117]
Currently, in order to download the platform one must specify the exact version number in the both the path of the url and path of the jar file

`https://github.com/Raphtory/Raphtory/releases/download/0.1/raphtory-v0.1.jar` 

Rather than this, it would be more usable to remove the version number from the jar file (as seen below), this way a user can be guaranteed to always pull the latest jar without worrying about version numbers, for the version they can simply change the `latest` value

`https://github.com/Raphtory/Raphtory/releases/latest/download/raphtory.jar`

**Comment by Haaroon** [comment]
need to add this as well https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/linking-to-releases

**Comment by miratepuffin** [comment]
Fixed with 0.4.0 Release
