### ISSUE TITLE
Logging  Considerations

### ISSUE THREAD

**Issue by iamsmkr** [Raphtory/Raphtory#150]
This issue lists down some of the logging considerations for Raphtory:

## ActorLogging considerations
- Scala string interpolations and concatenations in debug logs will always be evaluated even if `DEBUG` loglevel is disabled. This is evidently undesirable in production deployments.
    ```scala
    case class SimpleDebugLog(msg: String = "Simple debug log") {
        override def toString = {
            println(msg)
            msg
        }
    }

    context.log.debug(s"Message: ${SimpleDebugLog()}")
    context.log.debug(s"Message: " + SimpleDebugLog())
    ```

    This  could though be avoided by using akka built-in logging, as shown below:
    ```scala
    context.log.debug("Message received: {}", SimpleDebugLog())
    ```

    In practice it is usually difficult to stick to a certain style and difficult to catch in code reviews.

- To enable loglevel filtering in the logger backend configuration file, such as `logback`, akka log config must always be set to `DEBUG`. In other words, if you have not set `akka.loglevel` to `DEBUG` log entries from the classic logging API may never reach the logger backend at all. This however results in debug logs being evaluated always. This could clearly bog down the system unnecessarily. This could be avoided by switching from default Akka logger over to SLF4J logger available in the `akka-slf4j` module while making sure to always enable `logging-filter` configuration as shown below. This configuration will filter the log events using the backend configuration (e.g. logback.xml) before they are published to the event bus and could be safely used in production.
    ```sh
    akka {
        loggers = ["akka.event.slf4j.Slf4jLogger"]
        loglevel = "DEBUG"
        logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
    }
    ```
   **Note:** `akka-typed` brings SLF4J logger and the aforementioned `loggers` and `logging-filter` configurations along out-of-the-box. In which case, loglevel is always dictated by the `logback.xml` itself.

- Asynchronous logging with `ActorLogging` is achieved by sending log events to event handle actor. This log event handler actor however makes use of **default akka dispatcher**. It means excess logging could effect the system adversely. The recommended approach as per Akka documentation is to make use of SLF4J API directly while making sure to use `AsyncAppender` so as to avoid, blocking log write operations.
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>

        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>myapp.log</file>
            <immediateFlush>false</immediateFlush>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <fileNamePattern>myapp_%d{yyyy-MM-dd}.log</fileNamePattern>
            </rollingPolicy>
            <encoder>
                <pattern>[%date{ISO8601}] [%level] [%logger] [%marker] [%thread] - %msg MDC: {%mdc}%n</pattern>
            </encoder>
        </appender>

        <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
            <queueSize>8192</queueSize>
            <neverBlock>true</neverBlock>
            <appender-ref ref="FILE" />
        </appender>

        <root level="INFO">
            <appender-ref ref="ASYNC"/>
        </root>
    </configuration>
    ```
    **Note:** By default, `AsyncAppender` will drop events of level TRACE, DEBUG and INFO if its queue is 80% full. This strategy has an amazingly favorable effect on performance at the cost of event loss.

## MDC considerations
In raphtory, if there is a need to distinguish logs based on correlation ids, we may consider implementing MDC based logging.

## Using a standard logging across Raphtory
As of now, raphtory seem to be using multiple ways to implement logging, such as `Kamon`, `ActorLogging` and `ScalaLogging`. We could preferably decide on a single approach to log across Raphtory.

## References
http://logback.qos.ch/manual/appenders.html

https://doc.akka.io/docs/akka/current/logging.html

https://manuel.bernhardt.io/2016/08/31/akka-anti-patterns-logging-the-wrong-way/

**Comment by miratepuffin** [comment]
Hi @iamsmkr, thanks for making such extensive notes on this! We should probably agree on a standard as a group, but would you be happy to lead the charge here and fix up after we have all discussed?

**Comment by iamsmkr** [comment]
@miratepuffin Currently, I am searching for standard practices to implement MDC propagation within Akka/Scala Futures ecosystem. This would help me settle for a logging approach to stick with across Raphtory, if MDC based logging is even needed. But yes, I would be more than happy to take a lead on this! Thanks.

**Comment by miratepuffin** [comment]
Thanks @iamsmkr I think we have fixed this now :D
