### ISSUE TITLE
Spout not ingesting when container is started last in docker swarm

### ISSUE THREAD

**Issue by imanehaf** [Raphtory/Raphtory#152]
I'm looking at a recurrent issue where, when run as a docker swarm, the spout container starts last and stays idle (no data sent to the rest of the swarm). A restart of the swarm is a quick fix but I was wondering if it could be scheduled in a way that ensures this is not an issue anymore.

**Comment by miratepuffin** [comment]
I believe this has been fixed now that we have covered all components with the replicator.

**Comment by richardclegg** [comment]
I am on annual leave until 28th June.
