### ISSUE TITLE
Suggestion: return algorithm results by vertex "name" property rather than hashed ID?

### ISSUE THREAD

**Issue by narnolddd** [Raphtory/Raphtory#213]
Issue: 
Many current algos return hashed vertex ID + vertex algorithm property (e.g. connected components label) , hashed vertex ID is not really useful for if doing any post-processing of Raphtory results in python etc (unless you're looking at aggregated statistics of the graph like number of connected components etc)

Example:
```
.select(vertex => Row(vertex.ID(),vertex.getState[Long]("cclabel")))
```

Possible quick fix:
Have all algorithms check if vertex has property "name" and then return name + vertex algorithm property, otherwise hashed ID instead of name  (I think some of the algorithms have this + I am happy to do this and make PR if it sounds good?) 
For example the above would be replaced by
```
.select(vertex => Row(vertex.getPropertyOrElse("name",vertex.ID()),vertex.getState[Long]("cclabel")))
```

Possible longer term idea:
Have an extra parameter supplied to the graph algorithm or query asking which node prop should be returned instead of ID, defaulting to "name", which itself defaults to hashed id if no name. Might be a bit too restrictive though 🤔 

What do you think?

**Comment by ljeub-pometry** [comment]
This seems to be fixed since vertex.name is now implemented and used as the identifier.
