### ISSUE TITLE
Dealing with duplicate elements that have the exact same timestamp

### ISSUE THREAD

**Issue by Haaroon** [Raphtory/Raphtory#471]
In some datasets, such as blockchain data, you can have transactions that occur at the exact same Unix time, this is because blocks hold multiple transactions, that have occurred within the past N or so minutes. These transactions have to be confirmed by the network. A user can buy an item and then sell that item within the same block. Potential use case maybe they are doing an arbitrage. 

Technically the transactions have an order in the block, but this is not accounted for in the timestamp. e.g tx1 may appear before tx2 in the order, but they have the same timestamps. 

Data like this causes raphtory to crash 

`16:11:23.318 [spawner-akka.actor.default-dispatcher-7] INFO  com.raphtory.internals.components.querymanager.QueryManager - Query 'CycleMania_8894781737263084781' received, your job ID is 'CycleMania_8894781737263084781'.java.lang.Error: Mismatched duplicate element: old=(1540436348,0xfbf193668516edb858e1ac8b95a562d2a8583418e9dd3cf523b66e6a7426e17c), new=(1540436348,0x3cd1d9caa9d06e40aef1b052676c72b66d9de81d68dc0d0a0576fc0078a8dabd)at com.raphtory.internals.storage.pojograph.OrderedBuffer$OrderedAppend.sortedAppend(OrderedBuffer.scala:34)at com.raphtory.internals.storage.pojograph.entities.internal.MutableProperty.update(MutableProperty.scala:27)`

linked by DEV-1034

**Comment by ljeub-pometry** [comment]
It is now possible to specify a secondary index at ingestion time which should make it possible to handle this case correctly.
