### ISSUE TITLE
Write test for Page Rank Algorithm

### ISSUE THREAD

**Issue by rachchan** [Raphtory/Raphtory#562]
We need a test in our [algorithm test package](https://github.com/Raphtory/Raphtory/tree/master/core/src/test/scala/com/raphtory/algorithms) for the [Page Rank Algorithm](https://github.com/Raphtory/Raphtory/blob/development/core/src/main/scala/com/raphtory/algorithms/generic/centrality/PageRank.scala).

**Bonus: write test for the [Weighted Page Rank Algorithm](https://github.com/Raphtory/Raphtory/blob/development/core/src/main/scala/com/raphtory/algorithms/generic/centrality/WeightedPageRank.scala) in the same test file**

[ConnectedComponentsTest.scala](https://github.com/Raphtory/Raphtory/blob/master/core/src/test/scala/com/raphtory/algorithms/ConnectedComponentsTest.scala) is a good example of how tests work in Raphtory. The input test data and output data to expect goes in its own folder in this [resource package](https://github.com/Raphtory/Raphtory/tree/master/core/src/test/resources).

**Comment by ljeub-pometry** [comment]
Basic PageRank test is done in #565, weighted PageRank test is still missing.
